name: Run Script
on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run command - POST Koyeb reredeploy API
        run: |
          curl -X POST https://app.koyeb.com/v1/services/${{ secrets.KOYEB_SERVICE_ID }}/redeploy
          -H "Authorization: Bearer ${{ secrets.KOYEB_TOKEN }}"
          -H "Content-Type: application/json"
          -d '{
            "deployment_group": "prod",
            "sha": "",
            "use_cache": false,
            "skip_build": false
          }' -s -o /dev/null -w "%{http_code}"
          # if [ $? -eq 0 ]; then
          #     echo "Call Koyeb API Done! ( $(date +'%Y-%m-%d %H:%M:%S') )"
          # else
          #     echo "Failed, exit code: $?"
          # fi

      - name: Run script
        run: |
          bash ./data/script.sh
