name: Run Script
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: 執行指令
        run: |
          curl -s "${{ secrets.API_URL }}" > /dev/null
          if [ $? -eq 0 ]; then
              echo "Done!"
          else
              echo "Failed, exit code: $?"
          fi

      - name: 執行腳本
        run: |
          bash ./data/script.sh
