name: Run Script
on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 執行指令 - POST Koyeb reredeploy API
        run: |
          curl --location 'https://app.koyeb.com/v1/services/${{ secrets.KOYEB_SERVICE_ID }}/redeploy' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.KOYEB_TOKEN }}' \
          --data '{
            "deployment_group": "prod",
            "sha": "",
            "use_cache": false,
            "skip_build": false
          }' > /dev/null
          if [ $? -eq 0 ]; then
              echo "Call Koyeb API Done! ( $(date +'%Y-%m-%d %H:%M:%S') )"
          else
              echo "Failed, exit code: $?"
          fi

      - name: 執行腳本
        run: |
          bash ./data/script.sh
